// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fstuymynrtnhyyackpzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdHV5bXlucnRuaHl5YWNrcHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjA1NjgsImV4cCI6MjA3Njc5NjU2OH0.nhXBbXWssxHKVt5f8k0sW2wSNLWKi_Od06u6i6TdEFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);